name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t 77z77/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true 77z77/react-test npm test
 
      - run: docker build -t 77z77/multi-client ./client
      - run: docker build -t 77z77/multi-nginx ./nginx
      - run: docker build -t 77z77/multi-server ./server
      - run: docker build -t 77z77/multi-worker ./worker
 
      - run: docker push 77z77/multi-client
      - run: docker push 77z77/multi-nginx
      - run: docker push 77z77/multi-server
      - run: docker push 77z77/multi-worker
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 